

alias b := build
alias f := flash
build:
  cargo build --release

flash:
  cargo build --release
  probe-rs run --chip STM32F411CEUx target/thumbv7em-none-eabihf/release/bdshot-simple-stm32-direct --connect-under-reset
